### ISSUE TITLE
You archived the twist downloader and sayd you fixed it.

### ISSUE THREAD

**Issue by ghost** [ThatNerdyPikachu/switcharoo#1]
The same error i had still appears with the new API Key.

**Comment by ghost** [comment]
@ThatNerdyPikachu

**Comment by ghost** [comment]
Its now getting the anime names n stuff but when downloading its only downloading 162kb of each episode, rendering it useless.
![image](https://user-images.githubusercontent.com/46395233/71377556-6fa39d00-25c5-11ea-98cf-33815fd8f2f3.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46395233/71377575-7f22e600-25c5-11ea-95fe-deb24ebec1f5.png)

**Comment by ghost** [comment]
Could you please fix it for me ?

**Comment by nixdaemon** [comment]
use animebytes lol @KoroFX. For the record, filing issues about archived projects in a completely separate project isn't the best look for your case. In fact it's an asshole move. Quit it.

**Comment by ghost** [comment]
No, i rather use another twix downloader from a guy that actually fucking cares about the shit he makes. https://github.com/phanirithvij/twist.moe

**Comment by nixdaemon** [comment]
*entitlement intensifies*

**Comment by ThatNerdyPikachu** [comment]
@KoroFX Actually, I'm a girl :)
